/**********************************/
/* Table Name: 텍스트마이닝 */
/**********************************/
DROP TABLE TM_CONTENTS CASCADE CONSTRAINTS; -- 자식 무시하고 삭제 가능
DROP TABLE TM_CONTENTS;

CREATE TABLE TM_CONTENTS(
		TCON_NO NUMBER(10) NOT NULL PRIMARY KEY,
		CATE_NO NUMBER(10),     -- FK
		ACC_NO NUMBER(10),      -- FK
		TCON_NAME VARCHAR2(100) NOT NULL,
		TCON_CONTENTS VARCHAR2(3000),
		TCON_VIEWS NUMBER(7) DEFAULT 0 NOT NULL,
		TCON_BOOKCNT NUMBER(7) DEFAULT 0 NOT NULL,
        TCON_BOOKMARK CHAR(1) DEFAULT 'N' NOT NULL,
		TCON_COMMENT NUMBER(7) DEFAULT 0 NOT NULL,
		TCON_DATE DATE NOT NULL,
        WORD VARCHAR2(30)             NULL,
  FOREIGN KEY (CATE_NO) REFERENCES CATEGORY (CATE_NO),
  FOREIGN KEY (ACC_NO) REFERENCES ACCOUNT (ACC_NO)
);

COMMENT ON TABLE TM_CONTENTS is '텍스트마이닝';
COMMENT ON COLUMN TM_CONTENTS.TCON_NO is '텍스트마이닝 번호';
COMMENT ON COLUMN TM_CONTENTS.CATE_NO is '카테고리 번호';
COMMENT ON COLUMN TM_CONTENTS.ACC_NO is '회원 번호';
COMMENT ON COLUMN TM_CONTENTS.TCON_NAME is '제목';
COMMENT ON COLUMN TM_CONTENTS.TCON_CONTENTS is '내용';
COMMENT ON COLUMN TM_CONTENTS.TCON_VIEWS is '조회수';
COMMENT ON COLUMN TM_CONTENTS.TCON_BOOKMARK is '북마크';
COMMENT ON COLUMN TM_CONTENTS.TCON_BOOKCNT is '북마크수';
COMMENT ON COLUMN TM_CONTENTS.TCON_COMMENT is '댓글수';
COMMENT ON COLUMN TM_CONTENTS.TCON_DATE is '등록일';
COMMENT ON COLUMN TM_CONTENTS.WORD is '검색어';

DROP SEQUENCE TM_CONTENTS_SEQ;

CREATE SEQUENCE TM_CONTENTS_SEQ
  START WITH 1              -- 시작 번호
  INCREMENT BY 1            -- 증가값
  MAXVALUE 9999999999       -- 최대값: 9999999999 --> NUMBER(10) 대응
  CACHE 2                   -- 2번은 메모리에서만 계산
  NOCYCLE;                  -- 다시 1부터 생성되는 것을 방지
  
commit;
SELECT * FROM tm_contents;


-- 등록
INSERT INTO tm_contents(tcon_no, cate_no, acc_no, tcon_name, tcon_contents, tcon_views, tcon_bookmark, tcon_bookcnt, tcon_date, word)
VALUES(TM_CONTENTS_SEQ.nextval, 5, 3, '달리 데이터마이닝', '데이터 텍스트마이닝 어려워용', 0, 'N', 0, sysdate, '텍스트마이닝');
